### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by alan-czajkowski** [wunzeco/ansible-elasticsearch-curator#1]
```
TASK [ansible-elasticsearch-curator : Create elasticsearch-curator actions config file] *******************************************************************************************
fatal: [xxxxxxxx.xxxx.com]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
```

**Comment by mplachter** [comment]
@alan-czajkowski Can you show an example of your vars for **elasticsearch_curator_actions:**

**Comment by alan-czajkowski** [comment]
```
    elasticsearch_curator_version: "5.3.0"
    elasticsearch_curator_client_hosts: "localhost"
    elasticsearch_curator_client_http_auth: "elastic:abcxyz"
    elasticsearch_curator_client_master_only: True    # if you want to curator to run ONLY on master
    elasticsearch_curator_actions:
      - action: delete_indices
        description: >-
          Delete indices older than 45 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: logstash-
            exclude:
          - filtertype: age
            source: name
            direction: older
            timestring: "'%Y.%m.%d'"
            unit: days
            unit_count: 45
            exclude:
    elasticsearch_curator_cron_job:
      description: "Curate Elasticsearch Indices once per week"
      minute:  0
      hour:    0
      day:     '*'
      weekday: 6
      month:   '*'
```

**Comment by mplachter** [comment]
Hey @alan-czajkowski,
I tested your vars with the role and they worked like a charm.
Can you add these vars to the role step like this.

```
- name: ES Curator
  hosts: all
  become: true

  vars:
    elasticsearch_curator_version: "5.3.0"
    elasticsearch_curator_client_hosts: "localhost"
    elasticsearch_curator_client_http_auth: "elastic:abcxyz"
    elasticsearch_curator_client_master_only: True    # if you want to curator to run ONLY on master
    elasticsearch_curator_actions:
      - action: delete_indices
        description: >-
          Delete indices older than 45 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: logstash-
            exclude:
          - filtertype: age
            source: name
            direction: older
            timestring: "'%Y.%m.%d'"
            unit: days
            unit_count: 45
            exclude:
    elasticsearch_curator_cron_job:
      description: "Curate Elasticsearch Indices once per week"
      minute:  0
      hour:    0
      day:     '*'
      weekday: 6
      month:   '*'

  roles:
    - wunzeco.elasticsearch-curator
```

and let me know if it still fails,
Thanks.
